#
_XDCBUILDCOUNT = 0
ifneq (,$(findstring path,$(_USEXDCENV_)))
override XDCPATH = /home/nadagill/project/ezsdk/component-sources/bios_6_33_05_46/packages;/home/nadagill/project/ezsdk/component-sources/framework_components_3_22_01_07/packages;/home/nadagill/project/ezsdk/component-sources/ipc_1_24_03_32/packages;/home/nadagill/project/ezsdk/component-sources/syslink_2_20_02_20/packages;/home/nadagill/project/ezsdk/component-sources/xdctools_3_23_03_53/packages;/home/nadagill/project/ezsdk/component-sources/codec_engine_3_22_01_06/packages;/home/nadagill/project/ezsdk/component-sources/omx_05_02_00_48/src;/home/nadagill/project/ezsdk/component-sources/omx_05_02_00_48/src/ti/omx/interfaces/openMaxv11;/home/nadagill/project/ezsdk/component-sources/ivahd_h264enc_02_00_02_02_production/packages;/home/nadagill/project/ezsdk/component-sources/ivahd_h264vdec_02_00_07_00_production/packages;/home/nadagill/project/ezsdk/component-sources/ivahd_mpeg2vdec_01_00_05_00_production/packages;/home/nadagill/project/ezsdk/component-sources/c674x_mp3dec_01_41_00_00_elf/packages;/home/nadagill/project/ezsdk/component-sources/c674x-aaclcdec_01_41_00_00_elf/packages;/home/nadagill/project/ezsdk/component-sources/codecs-dm816x_5_00_00_00/packages;/home/nadagill/project/ezsdk/component-sources/omx_05_02_00_48/src/ti/omx/comp/omxbase;/home/nadagill/project/ezsdk/component-sources/omx_05_02_00_48/src/ti/omx/omxcore;/home/nadagill/project/ezsdk/component-sources/ivahd_hdvicp20api_01_00_00_19_production/packages;/home/nadagill/project/ezsdk/component-sources/osal_1_22_01_09/packages;/home/nadagill/project/ezsdk/component-sources/xdais_7_22_00_03/packages;/home/nadagill/project/ezsdk/component-sources/linuxutils_3_22_00_02/packages;/home/nadagill/project/ezsdk/component-sources/uia_1_01_01_14/packages;/home/nadagill/project/ezsdk/component-sources/ivahd_mpeg4enc_01_00_00_05_production/packages;/home/nadagill/project/ezsdk/component-sources/ivahd_mpeg4vdec_01_00_04_00_production/packages;/home/nadagill/project/ezsdk/component-sources/ivahd_vc1vdec_01_00_00_07_production/packages;/home/nadagill/project/ezsdk/component-sources/ivahd_jpegvdec_01_00_04_00_production/packages;/home/nadagill/project/ezsdk/component-sources/c674x_aaclcenc_01_00_01_00_elf/packages;
override XDCROOT = /home/nadagill/project/ezsdk/component-sources/xdctools_3_23_03_53
override XDCBUILDCFG = /home/nadagill/project/ezsdk/component-sources/omx_05_02_00_48/src/ti/omx/build/config_dsp.bld
endif
ifneq (,$(findstring args,$(_USEXDCENV_)))
override XDCARGS = core=vpss_m3 profile=debug
override XDCTARGETS = 
endif
#
ifeq (0,1)
PKGPATH = /home/nadagill/project/ezsdk/component-sources/bios_6_33_05_46/packages;/home/nadagill/project/ezsdk/component-sources/framework_components_3_22_01_07/packages;/home/nadagill/project/ezsdk/component-sources/ipc_1_24_03_32/packages;/home/nadagill/project/ezsdk/component-sources/syslink_2_20_02_20/packages;/home/nadagill/project/ezsdk/component-sources/xdctools_3_23_03_53/packages;/home/nadagill/project/ezsdk/component-sources/codec_engine_3_22_01_06/packages;/home/nadagill/project/ezsdk/component-sources/omx_05_02_00_48/src;/home/nadagill/project/ezsdk/component-sources/omx_05_02_00_48/src/ti/omx/interfaces/openMaxv11;/home/nadagill/project/ezsdk/component-sources/ivahd_h264enc_02_00_02_02_production/packages;/home/nadagill/project/ezsdk/component-sources/ivahd_h264vdec_02_00_07_00_production/packages;/home/nadagill/project/ezsdk/component-sources/ivahd_mpeg2vdec_01_00_05_00_production/packages;/home/nadagill/project/ezsdk/component-sources/c674x_mp3dec_01_41_00_00_elf/packages;/home/nadagill/project/ezsdk/component-sources/c674x-aaclcdec_01_41_00_00_elf/packages;/home/nadagill/project/ezsdk/component-sources/codecs-dm816x_5_00_00_00/packages;/home/nadagill/project/ezsdk/component-sources/omx_05_02_00_48/src/ti/omx/comp/omxbase;/home/nadagill/project/ezsdk/component-sources/omx_05_02_00_48/src/ti/omx/omxcore;/home/nadagill/project/ezsdk/component-sources/ivahd_hdvicp20api_01_00_00_19_production/packages;/home/nadagill/project/ezsdk/component-sources/osal_1_22_01_09/packages;/home/nadagill/project/ezsdk/component-sources/xdais_7_22_00_03/packages;/home/nadagill/project/ezsdk/component-sources/linuxutils_3_22_00_02/packages;/home/nadagill/project/ezsdk/component-sources/uia_1_01_01_14/packages;/home/nadagill/project/ezsdk/component-sources/ivahd_mpeg4enc_01_00_00_05_production/packages;/home/nadagill/project/ezsdk/component-sources/ivahd_mpeg4vdec_01_00_04_00_production/packages;/home/nadagill/project/ezsdk/component-sources/ivahd_vc1vdec_01_00_00_07_production/packages;/home/nadagill/project/ezsdk/component-sources/ivahd_jpegvdec_01_00_04_00_production/packages;/home/nadagill/project/ezsdk/component-sources/c674x_aaclcenc_01_00_01_00_elf/packages;/home/nadagill/project/ezsdk/component-sources/xdctools_3_23_03_53/packages;../..
HOSTOS = Linux
endif
