#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#

unexport MAKEFILE_LIST
MK_NOGENDEPS := $(filter clean,$(MAKECMDGOALS))
override PKGDIR = ti/timmosal
XDCINCS = -I. -I$(strip $(subst ;, -I,$(subst $(space),\$(space),$(XPKGPATH))))
XDCCFGDIR = package/cfg/

#
# The following dependencies ensure package.mak is rebuilt
# in the event that some included BOM script changes.
#
ifneq (clean,$(MAKECMDGOALS))
/home/nadagill/project/ezsdk/component-sources/xdctools_3_23_03_53/include/utils.tci:
package.mak: /home/nadagill/project/ezsdk/component-sources/xdctools_3_23_03_53/include/utils.tci
/home/nadagill/project/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/xdc.tci:
package.mak: /home/nadagill/project/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/xdc.tci
/home/nadagill/project/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/template.xs:
package.mak: /home/nadagill/project/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/template.xs
/home/nadagill/project/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/om2.xs:
package.mak: /home/nadagill/project/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/om2.xs
/home/nadagill/project/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/xmlgen.xs:
package.mak: /home/nadagill/project/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/xmlgen.xs
/home/nadagill/project/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/xmlgen2.xs:
package.mak: /home/nadagill/project/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/xmlgen2.xs
/home/nadagill/project/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/IPackage.xs:
package.mak: /home/nadagill/project/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/IPackage.xs
/home/nadagill/project/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/package.xs:
package.mak: /home/nadagill/project/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/package.xs
/home/nadagill/project/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/services/global/Clock.xs:
package.mak: /home/nadagill/project/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/services/global/Clock.xs
/home/nadagill/project/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/services/global/Trace.xs:
package.mak: /home/nadagill/project/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/services/global/Trace.xs
/home/nadagill/project/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/bld/bld.js:
package.mak: /home/nadagill/project/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/bld/bld.js
/home/nadagill/project/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/bld/BuildEnvironment.xs:
package.mak: /home/nadagill/project/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/bld/BuildEnvironment.xs
/home/nadagill/project/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/bld/PackageContents.xs:
package.mak: /home/nadagill/project/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/bld/PackageContents.xs
/home/nadagill/project/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/bld/_gen.xs:
package.mak: /home/nadagill/project/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/bld/_gen.xs
/home/nadagill/project/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/bld/Library.xs:
package.mak: /home/nadagill/project/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/bld/Library.xs
/home/nadagill/project/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/bld/Executable.xs:
package.mak: /home/nadagill/project/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/bld/Executable.xs
/home/nadagill/project/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/bld/Repository.xs:
package.mak: /home/nadagill/project/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/bld/Repository.xs
/home/nadagill/project/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/bld/Configuration.xs:
package.mak: /home/nadagill/project/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/bld/Configuration.xs
/home/nadagill/project/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/bld/Script.xs:
package.mak: /home/nadagill/project/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/bld/Script.xs
/home/nadagill/project/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/bld/Manifest.xs:
package.mak: /home/nadagill/project/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/bld/Manifest.xs
/home/nadagill/project/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/bld/Utils.xs:
package.mak: /home/nadagill/project/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/bld/Utils.xs
/home/nadagill/project/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/bld/ITarget.xs:
package.mak: /home/nadagill/project/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/bld/ITarget.xs
/home/nadagill/project/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/bld/ITarget2.xs:
package.mak: /home/nadagill/project/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/bld/ITarget2.xs
/home/nadagill/project/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/bld/ITargetFilter.xs:
package.mak: /home/nadagill/project/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/bld/ITargetFilter.xs
/home/nadagill/project/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/bld/package.xs:
package.mak: /home/nadagill/project/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/bld/package.xs
/home/nadagill/project/ezsdk/component-sources/omx_05_02_00_48/src/ti/omx/build/config_dsp.bld:
package.mak: /home/nadagill/project/ezsdk/component-sources/omx_05_02_00_48/src/ti/omx/build/config_dsp.bld
/home/nadagill/project/ezsdk/component-sources/omx_05_02_00_48/src/ti/omx/build/dspsubsys.xs:
package.mak: /home/nadagill/project/ezsdk/component-sources/omx_05_02_00_48/src/ti/omx/build/dspsubsys.xs
/home/nadagill/project/ezsdk/component-sources/omx_05_02_00_48/src/ti/omx/build/MemSegmentDefinition.xs:
package.mak: /home/nadagill/project/ezsdk/component-sources/omx_05_02_00_48/src/ti/omx/build/MemSegmentDefinition.xs
/home/nadagill/project/ezsdk/component-sources/xdctools_3_23_03_53/packages/ti/targets/ITarget.xs:
package.mak: /home/nadagill/project/ezsdk/component-sources/xdctools_3_23_03_53/packages/ti/targets/ITarget.xs
/home/nadagill/project/ezsdk/component-sources/xdctools_3_23_03_53/packages/ti/targets/C28_large.xs:
package.mak: /home/nadagill/project/ezsdk/component-sources/xdctools_3_23_03_53/packages/ti/targets/C28_large.xs
/home/nadagill/project/ezsdk/component-sources/xdctools_3_23_03_53/packages/ti/targets/C28_float.xs:
package.mak: /home/nadagill/project/ezsdk/component-sources/xdctools_3_23_03_53/packages/ti/targets/C28_float.xs
/home/nadagill/project/ezsdk/component-sources/xdctools_3_23_03_53/packages/ti/targets/package.xs:
package.mak: /home/nadagill/project/ezsdk/component-sources/xdctools_3_23_03_53/packages/ti/targets/package.xs
/home/nadagill/project/ezsdk/component-sources/xdctools_3_23_03_53/packages/ti/targets/elf/ITarget.xs:
package.mak: /home/nadagill/project/ezsdk/component-sources/xdctools_3_23_03_53/packages/ti/targets/elf/ITarget.xs
/home/nadagill/project/ezsdk/component-sources/xdctools_3_23_03_53/packages/ti/targets/elf/TMS470.xs:
package.mak: /home/nadagill/project/ezsdk/component-sources/xdctools_3_23_03_53/packages/ti/targets/elf/TMS470.xs
/home/nadagill/project/ezsdk/component-sources/xdctools_3_23_03_53/packages/ti/targets/elf/package.xs:
package.mak: /home/nadagill/project/ezsdk/component-sources/xdctools_3_23_03_53/packages/ti/targets/elf/package.xs
package.mak: package.bld
/home/nadagill/project/ezsdk/component-sources/omx_05_02_00_48/src/ti/omx/build/common.bld:
package.mak: /home/nadagill/project/ezsdk/component-sources/omx_05_02_00_48/src/ti/omx/build/common.bld
endif

ti.targets.elf.C674.rootDir ?= /home/nadagill/project/ezsdk/dsp-devkit/cgt6x_7_3_4
ti.targets.elf.packageBase ?= /home/nadagill/project/ezsdk/component-sources/xdctools_3_23_03_53/packages/ti/targets/elf/
.PRECIOUS: $(XDCCFGDIR)/%.oe674
.PHONY: all,e674 .dlls,e674 .executables,e674 test,e674
all,e674: .executables,e674
.executables,e674: .libraries,e674
.executables,e674: .dlls,e674
.dlls,e674: .libraries,e674
.libraries,e674: .interfaces
	@$(RM) $@
	@$(TOUCH) "$@"

.help::
	@$(ECHO) xdc test,e674
	@$(ECHO) xdc .executables,e674
	@$(ECHO) xdc .libraries,e674
	@$(ECHO) xdc .dlls,e674


all: .executables 
.executables: .libraries .dlls
.libraries: .interfaces

PKGCFGS := $(wildcard package.xs) package/build.cfg
.interfaces: package/package.xdc.inc package/package.defs.h package.xdc $(PKGCFGS)

-include package/package.xdc.dep
package/%.xdc.inc package/%_ti.timmosal.c package/%.defs.h: %.xdc $(PKGCFGS)
	@$(MSG) generating interfaces for package ti.timmosal" (because $@ is older than $(firstword $?))" ...
	$(XSRUN) -f xdc/services/intern/cmd/build.xs $(MK_IDLOPTS) -m package/package.xdc.dep -i package/package.xdc.inc package.xdc

ifeq (,$(MK_NOGENDEPS))
-include package/package.cfg.dep
endif

package/package.ext.xml: package/package.cfg.xdc.inc
package/package.cfg.xdc.inc: $(XDCROOT)/packages/xdc/cfg/cfginc.js package.xdc
	@$(MSG) generating schema include file list ...
	$(CONFIG) -f $(XDCROOT)/packages/xdc/cfg/cfginc.js ti.timmosal $@

ifneq (clean,$(MAKECMDGOALS))
package.mak:/home/nadagill/project/ezsdk/component-sources/codec_engine_3_22_01_06/packages/ti/sdo/ce/utils/libvers.xdt
/home/nadagill/project/ezsdk/component-sources/codec_engine_3_22_01_06/packages/ti/sdo/ce/utils/libvers.xdt:

endif
.libraries,e674 .libraries: lib/ti.timmosal.ae674

-include lib/ti.timmosal.ae674.mak
lib/ti.timmosal.ae674: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/ti.timmosal/package/package_ti.timmosal.oe674 package/lib/lib/ti.timmosal/./bios6/src/timm_osal_trace.oe674 package/lib/lib/ti.timmosal/./bios6/src/timm_osal_task.oe674 package/lib/lib/ti.timmosal/./bios6/src/timm_osal_semaphores.oe674 package/lib/lib/ti.timmosal/./bios6/src/timm_osal_pipes.oe674 package/lib/lib/ti.timmosal/./bios6/src/timm_osal_mutex.oe674 package/lib/lib/ti.timmosal/./bios6/src/timm_osal_memory.oe674 package/lib/lib/ti.timmosal/./bios6/src/timm_osal_events.oe674 package/lib/lib/ti.timmosal/./bios6/src/timm_osal.oe674 package/lib/lib/ti.timmosal/./StmLibrary/StmLibrary.oe674 package/lib/lib/ti.timmosal/./StmLibrary/STMHelper.oe674  into $@ ...
	$(ti.targets.elf.C674.rootDir)/bin/ar6x  rq $@   package/lib/lib/ti.timmosal/package/package_ti.timmosal.oe674 package/lib/lib/ti.timmosal/./bios6/src/timm_osal_trace.oe674 package/lib/lib/ti.timmosal/./bios6/src/timm_osal_task.oe674 package/lib/lib/ti.timmosal/./bios6/src/timm_osal_semaphores.oe674 package/lib/lib/ti.timmosal/./bios6/src/timm_osal_pipes.oe674 package/lib/lib/ti.timmosal/./bios6/src/timm_osal_mutex.oe674 package/lib/lib/ti.timmosal/./bios6/src/timm_osal_memory.oe674 package/lib/lib/ti.timmosal/./bios6/src/timm_osal_events.oe674 package/lib/lib/ti.timmosal/./bios6/src/timm_osal.oe674 package/lib/lib/ti.timmosal/./StmLibrary/StmLibrary.oe674 package/lib/lib/ti.timmosal/./StmLibrary/STMHelper.oe674 
lib/ti.timmosal.ae674: export C_DIR=
lib/ti.timmosal.ae674: PATH:=$(ti.targets.elf.C674.rootDir)/bin/:$(PATH)

clean,e674 clean::
	-$(RM) lib/ti.timmosal.ae674
test:;
%,copy:
	@$(if $<,,$(MSG) don\'t know how to build $*; exit 1)
	@$(MSG) cp $< $@
	$(RM) $@
	$(CP) $< $@
package_ti.timmosal.oe674,copy : package/lib/lib/ti.timmosal/package/package_ti.timmosal.oe674
package_ti.timmosal.se674,copy : package/lib/lib/ti.timmosal/package/package_ti.timmosal.se674
timm_osal_trace.oe674,copy : package/lib/lib/ti.timmosal/./bios6/src/timm_osal_trace.oe674
timm_osal_trace.se674,copy : package/lib/lib/ti.timmosal/./bios6/src/timm_osal_trace.se674
timm_osal_task.oe674,copy : package/lib/lib/ti.timmosal/./bios6/src/timm_osal_task.oe674
timm_osal_task.se674,copy : package/lib/lib/ti.timmosal/./bios6/src/timm_osal_task.se674
timm_osal_semaphores.oe674,copy : package/lib/lib/ti.timmosal/./bios6/src/timm_osal_semaphores.oe674
timm_osal_semaphores.se674,copy : package/lib/lib/ti.timmosal/./bios6/src/timm_osal_semaphores.se674
timm_osal_pipes.oe674,copy : package/lib/lib/ti.timmosal/./bios6/src/timm_osal_pipes.oe674
timm_osal_pipes.se674,copy : package/lib/lib/ti.timmosal/./bios6/src/timm_osal_pipes.se674
timm_osal_mutex.oe674,copy : package/lib/lib/ti.timmosal/./bios6/src/timm_osal_mutex.oe674
timm_osal_mutex.se674,copy : package/lib/lib/ti.timmosal/./bios6/src/timm_osal_mutex.se674
timm_osal_memory.oe674,copy : package/lib/lib/ti.timmosal/./bios6/src/timm_osal_memory.oe674
timm_osal_memory.se674,copy : package/lib/lib/ti.timmosal/./bios6/src/timm_osal_memory.se674
timm_osal_events.oe674,copy : package/lib/lib/ti.timmosal/./bios6/src/timm_osal_events.oe674
timm_osal_events.se674,copy : package/lib/lib/ti.timmosal/./bios6/src/timm_osal_events.se674
timm_osal.oe674,copy : package/lib/lib/ti.timmosal/./bios6/src/timm_osal.oe674
timm_osal.se674,copy : package/lib/lib/ti.timmosal/./bios6/src/timm_osal.se674
StmLibrary.oe674,copy : package/lib/lib/ti.timmosal/./StmLibrary/StmLibrary.oe674
StmLibrary.se674,copy : package/lib/lib/ti.timmosal/./StmLibrary/StmLibrary.se674
STMHelper.oe674,copy : package/lib/lib/ti.timmosal/./StmLibrary/STMHelper.oe674
STMHelper.se674,copy : package/lib/lib/ti.timmosal/./StmLibrary/STMHelper.se674

$(XDCCFGDIR)%.c $(XDCCFGDIR)%.h $(XDCCFGDIR)%.xdl: $(XDCCFGDIR)%.cfg .interfaces $(XDCROOT)/packages/xdc/cfg/Main.xs
	@$(MSG) "configuring $(_PROG_NAME) from $< ..."
	$(CONFIG) $(_PROG_XSOPTS) xdc.cfg $(_PROG_NAME) $(XDCCFGDIR)$*.cfg $(XDCCFGDIR)$*

.PHONY: release,ti_timmosal
ti_timmosal.tar.gz: package/package.bld.xml
ti_timmosal.tar.gz: package/package.ext.xml
ti_timmosal.tar.gz: package/package.rel.dot
ti_timmosal.tar.gz: package/build.cfg
ti_timmosal.tar.gz: package/package.xdc.inc
ti_timmosal.tar.gz: package/package.cfg.xdc.inc
ti_timmosal.tar.gz: lib/ti.timmosal.ae674
ifeq (,$(MK_NOGENDEPS))
-include package/rel/ti_timmosal.tar.gz.dep
endif
package/rel/ti_timmosal/ti/timmosal/package/package.rel.xml:

ti_timmosal.tar.gz: package/rel/ti_timmosal.xdc.inc package/rel/ti_timmosal/ti/timmosal/package/package.rel.xml
	@$(MSG) making release file $@ "(because of $(firstword $?))" ...
	-$(RM) $@
	$(call MKRELTAR,package/rel/ti_timmosal.xdc.inc,package/rel/ti_timmosal.tar.gz.dep)


release release,ti_timmosal: all ti_timmosal.tar.gz
clean:: .clean
	-$(RM) ti_timmosal.tar.gz
	-$(RM) package/rel/ti_timmosal.xdc.inc
	-$(RM) package/rel/ti_timmosal.tar.gz.dep

clean:: .clean
	-$(RM) .libraries .libraries,*
clean:: 
	-$(RM) .dlls .dlls,*
#
# The following clean rule removes user specified
# generated files or directories.
#

ifneq (clean,$(MAKECMDGOALS))
ifeq (,$(wildcard lib))
    $(shell $(MKDIR) lib)
endif
ifeq (,$(wildcard package))
    $(shell $(MKDIR) package)
endif
ifeq (,$(wildcard package/cfg))
    $(shell $(MKDIR) package/cfg)
endif
ifeq (,$(wildcard package/lib))
    $(shell $(MKDIR) package/lib)
endif
ifeq (,$(wildcard package/rel))
    $(shell $(MKDIR) package/rel)
endif
ifeq (,$(wildcard package/internal))
    $(shell $(MKDIR) package/internal)
endif
ifeq (,$(wildcard package/external))
    $(shell $(MKDIR) package/external)
endif
ifeq (,$(wildcard package/lib/lib))
    $(shell $(MKDIR) package/lib/lib)
endif
ifeq (,$(wildcard package/lib/lib/ti.timmosal))
    $(shell $(MKDIR) package/lib/lib/ti.timmosal)
endif
ifeq (,$(wildcard package/lib/lib/ti.timmosal/package))
    $(shell $(MKDIR) package/lib/lib/ti.timmosal/package)
endif
ifeq (,$(wildcard package/lib/lib/ti.timmosal/bios6))
    $(shell $(MKDIR) package/lib/lib/ti.timmosal/bios6)
endif
ifeq (,$(wildcard package/lib/lib/ti.timmosal/bios6/src))
    $(shell $(MKDIR) package/lib/lib/ti.timmosal/bios6/src)
endif
ifeq (,$(wildcard package/lib/lib/ti.timmosal/StmLibrary))
    $(shell $(MKDIR) package/lib/lib/ti.timmosal/StmLibrary)
endif
endif
clean::
	-$(RMDIR) package


clean:: 
	-$(RM) package/ti.timmosal.pjt
